### ISSUE TITLE
Certbot can't work with spaces between multiple domains

### ISSUE THREAD

**Issue by Deroswent** [robertdebock/ansible-role-certbot#5]
## Describe the bug

Hello. Thank you for yor work.
Some little bug in task below (Managed or Standardalone variant). 
If use 2 or more domains in [default list format](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#defining-variables-as-lists), like:

```
# You can have multiple domains, as a list to request a certificate for.
certbot_domains:
  - site1.com
  - site2.com
```
or use vars like

```
# You can have multiple domains, as a list to request a certificate for.
certbot_domains:
 - {{ domains_from_host_vars }}
```

this line from your task `--domain {{ certbot_domains| join(' --domain ') }}`   make spaces between domains, its problem. Certbot can't work with spaces between domains.

The command that this task forms: `certbot --noninteractive --nginx --agree-tos --email admin@site1.com  --domain site1.com, site2.com`

If you try start this command in console, you'll receive an error `Requested domain  is not a FQDN because it contains an empty label.`

Right command must be witout space between domains:

`certbot --noninteractive --nginx --agree-tos --email admin@site1.com  --domain site1.com,site2.com`

## Playbook

```
- name: get and install certificates (Managed)
  ansible.builtin.command:
    cmd: |
      certbot --noninteractive
      --{{ certbot_system }}
      --domain {{ certbot_domains| join(' --domain ') }}
      --agree-tos
      --email {{ certbot_email }}
    creates: /etc/letsencrypt/accounts
  when:
    - certbot_ci_mode is not defined
    - certbot_system != "standalone"

```

## Output debug mode

TASK [robertdebock.nginx_certbot : get and install certificates (Managed)] **************************************************************************************************************************
task path: /home/nion/.ansible/roles/robertdebock.nginx_certbot/tasks/main.yml:110
[vps-uk] => {"changed": false, "cmd": ["certbot", "--noninteractive", "--nginx", "--domain", "[site1.com", "site2.com]", "--agree-tos", "--email", "admin@site1.com", "--no-redirect"], "delta": null, "end": null, "msg": ******************************

## Environment

- Control node OS: [e.g. Debian 9] (`cat /etc/os-release`)

```
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```
- Control node Ansible version: 

```
ansible [core 2.11.6] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/nion/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/nion/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Oct 10 2021, 15:13:22) [GCC 11.1.0]
  jinja version = 3.0.3
  libyaml = True

```
- Managed node OS: [e.g. CentOS 7] (`cat /etc/os-release`)

Tried Ubuntu 20.04 LTS, Debian 10. Using nginx in var:

```
# The certbot can configure either "apache", "haproxy", "nginx" or run "standalone".
certbot_system: nginx
```

**Comment by robertdebock** [comment]
Thanks for the issue; I did not know this, you saved the day!

A new release is coming with this fix inside.

**Comment by robertdebock** [comment]
New version released.
